# Generated by Django 5.2.1 on 2025-05-13 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sklep_gier', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='platforms',
        ),
        migrations.DeleteModel(
            name='Platform',
        ),
    ]
