# Generated by Django 5.2.1 on 2025-05-13 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sklep_gier', '0002_remove_game_platforms_delete_platform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
