# Generated by Django 5.2.1 on 2025-05-26 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sklep_gier', '0004_user_birth_date_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='e-mail address'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, max_length=150, null=True, unique=True, verbose_name='nickname'),
        ),
    ]
